services:
  api:
    build: .
    container_name: student_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=8080
      - ConnectionStrings__Default=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiresMinutes=60
      - Jwt__RefreshDays=14
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    container_name: student_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: studentuser
      POSTGRES_PASSWORD: superstudent
    ports:
      - "5432:5432"
    volumes:
      - security_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studentuser -d studentdb"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  security_data: